name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./reservation-management/pom.xml
          mvn clean package -f ./room-management/pom.xml
          mvn clean package -f ./checkinout-management/pom.xml
          mvn clean package -f ./payment-management/pom.xml

      - name: Docker Build and push for ReservationManagement
        uses: docker/build-push-action@v4
        with:
          context: ./reservation-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reservation-management:latest
            ghcr.io/${{ github.repository }}/reservation-management:${{ github.ref_name }}
            
      - name: Docker Build and push for RoomManagement
        uses: docker/build-push-action@v4
        with:
          context: ./room-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/room-management:latest
            ghcr.io/${{ github.repository }}/room-management:${{ github.ref_name }}
            
      - name: Docker Build and push for CheckinoutManagement
        uses: docker/build-push-action@v4
        with:
          context: ./checkinout-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/checkinout-management:latest
            ghcr.io/${{ github.repository }}/checkinout-management:${{ github.ref_name }}
            
      - name: Docker Build and push for PaymentManagement
        uses: docker/build-push-action@v4
        with:
          context: ./payment-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/payment-management:latest
            ghcr.io/${{ github.repository }}/payment-management:${{ github.ref_name }}
            
