---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-management
  labels:
    app: reservation-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-management
  template:
    metadata:
      labels:
        app: reservation-management
    spec:
      containers:
        - name: reservation-management
          image: username/reservation-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-management
  labels:
    app: room-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-management
  template:
    metadata:
      labels:
        app: room-management
    spec:
      containers:
        - name: room-management
          image: username/room-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkinout-management
  labels:
    app: checkinout-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkinout-management
  template:
    metadata:
      labels:
        app: checkinout-management
    spec:
      containers:
        - name: checkinout-management
          image: username/checkinout-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-management
  labels:
    app: payment-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-management
  template:
    metadata:
      labels:
        app: payment-management
    spec:
      containers:
        - name: payment-management
          image: username/payment-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: reservation-management
  labels:
    app: reservation-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: reservation-management


---


apiVersion: v1
kind: Service
metadata:
  name: room-management
  labels:
    app: room-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: room-management


---


apiVersion: v1
kind: Service
metadata:
  name: checkinout-management
  labels:
    app: checkinout-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: checkinout-management


---


apiVersion: v1
kind: Service
metadata:
  name: payment-management
  labels:
    app: payment-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: payment-management

